name: PHP CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.3
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306

      php:
        image: php:8.3

    steps:
    - uses: actions/checkout@v2

    - name: Run tests with phpunit
      run: |
        docker exec service_php_1 bash -c "
        pwd
        "